version: '3.3'

networks:
    app:

services:
    server:
        image: node
        container_name: server
        working_dir: /app/server
        restart: unless-stopped
        environment:
            - NODE_ENV=${NODE_ENV}
            - SERVER_HOST=${SERVER_HOST}
            - SERVER_PORT=${SERVER_PORT}
            - SERVER_PROTOCOL=${SERVER_PROTOCOL}
        expose:
            - ${SERVER_PORT}
        volumes:
            - ./server:/app/server
            - ./server/package.json:/app/server/package.json
            - ./server/package-lock.json:/app/server/package-lock.json
        command: >
            sh -c "npm install && npm run production"
        networks:
            - app

    client:
        image: node
        container_name: client
        working_dir: /app/client
        restart: unless-stopped
        environment:
            - NODE_ENV=${NODE_ENV}
            - REACT_APP_SERVER_HOST=${SERVER_HOST}
            - REACT_APP_SERVER_PORT=${SERVER_PORT}
            - REACT_APP_SERVER_PROTOCOL=${SERVER_PROTOCOL}
        volumes:
            - ./client:/app/client
            - ./client/package.json:/app/client/package.json
            - ./client/package-lock.json:/app/client/package-lock.json
        command: >
            sh -c "npm install && npm run build"
        networks:
            - app
